-- +goose Up

ALTER TABLE users ADD COLUMN IF NOT EXISTS word_hour INT DEFAULT 7;
ALTER TABLE users ADD COLUMN IF NOT EXISTS word_min INT DEFAULT 30;
ALTER TABLE users ADD COLUMN IF NOT EXISTS writing_hour INT DEFAULT 12;
ALTER TABLE users ADD COLUMN IF NOT EXISTS writing_min INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS media_hour INT DEFAULT 18;
ALTER TABLE users ADD COLUMN IF NOT EXISTS media_min INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS review_hour INT DEFAULT 21;
ALTER TABLE users ADD COLUMN IF NOT EXISTS review_min INT DEFAULT 30;

-- +goose Down

ALTER TABLE users DROP COLUMN IF EXISTS word_hour;
ALTER TABLE users DROP COLUMN IF EXISTS word_min;
ALTER TABLE users DROP COLUMN IF EXISTS writing_hour;
ALTER TABLE users DROP COLUMN IF EXISTS writing_min;
ALTER TABLE users DROP COLUMN IF EXISTS media_hour;
ALTER TABLE users DROP COLUMN IF EXISTS media_min;
ALTER TABLE users DROP COLUMN IF EXISTS review_hour;
ALTER TABLE users DROP COLUMN IF EXISTS review_min;
