-- +goose Up

ALTER TABLE words ADD COLUMN IF NOT EXISTS synonyms TEXT DEFAULT '';
ALTER TABLE words ADD COLUMN IF NOT EXISTS antonyms TEXT DEFAULT '';
ALTER TABLE words ADD COLUMN IF NOT EXISTS examples TEXT DEFAULT '';

ALTER TABLE users ADD COLUMN IF NOT EXISTS words_per_day INT DEFAULT 3;

ALTER TABLE users ADD COLUMN IF NOT EXISTS review_session_hour INT DEFAULT 14;
ALTER TABLE users ADD COLUMN IF NOT EXISTS review_session_min INT DEFAULT 0;

-- +goose Down

ALTER TABLE words DROP COLUMN IF EXISTS synonyms;
ALTER TABLE words DROP COLUMN IF EXISTS antonyms;
ALTER TABLE words DROP COLUMN IF EXISTS examples;

ALTER TABLE users DROP COLUMN IF EXISTS words_per_day;

ALTER TABLE users DROP COLUMN IF EXISTS review_session_hour;
ALTER TABLE users DROP COLUMN IF EXISTS review_session_min;
